# epicsEnvSet("ENGINEER",		   "")
# epicsEnvSet("LOCATION",		   "")
# epicsEnvSet("TOP",			   "${PWD}")
# epicsEnvSet("PORT",			   "")

# epicsEnvSet("EPICS_CA_AUTO_ADDR_LIST",   "")
# epicsEnvSet("EPICS_CA_ADDR_LIST", 	   "")
# epicsEnvSet("EPICS_CA_MAX_ARRAY_BYTES",  "")

# epicsEnvSet("CAM-IP",			   "")
# epicsEnvSet("UID_NUM", 		   "")
# epicsEnvSet("PREFIX", 		   "")
# epicsEnvSet("CTPREFIX", 		   "")
# epicsEnvSet("HOSTNAME", 		   "")
# epicsEnvSet("IOCNAME", 		   "")

# epicsEnvSet("QSIZE", 			   "")
# epicsEnvSet("NCHANS", 		   "")
# epicsEnvSet("HIST_SIZE", 		   "")
# epicsEnvSet("XSIZE", 			   "")
# epicsEnvSet("YSIZE",			   "")
# epicsEnvSet("NELMT", 			   "")
# epicsEnvSet("NDTYPE", 		   "")
# epicsEnvSet("NDFTVL", 		   "")
# epicsEnvSet("CBUFFS", 		   "")
